---

- name: Include tasks specific to Redhat distros.
  include_tasks: "{{ ansible_os_family }}.yml"
  when:
    - ansible_os_family == 'RedHat'

- name: Include tasks specific to Debian systems.
  include_tasks: "{{ ansible_os_family }}.yml"
  when:
    - ansible_os_family == 'Debian'

- name: copy over sshd_config template
  template:
   src: sshdconf.j2
   dest: /etc/ssh/sshd_config
   owner: root
   backup: yes
   mode: 0644
  notify: "restart sshd"
