---

- name: Include tasks specific to Redhat distros.
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
  when:
    - ansible_os_family == 'RedHat'

- name: Include tasks specific to Debian systems.
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
  when:
    - ansible_os_family == 'Debian'

- name: Copy over sshd_config template
  ansible.builtin.template:
    src: sshdconf.j2
    dest: /etc/ssh/sshd_config
    owner: root
    backup: yes
    mode: 0644
  notify: "Restart sshd"
