---
- name: Restart sshd
  service:
   name: sshd
   state: restarted
   enabled: yes
  when:
   - ansible_os_family == 'RedHat'
  # now I've added these listen directives, ssh will get restarted twice on some systems
  # raspbian 9 has no sshd, just ssh
  # debian9 has ssh and sshd
  # centos 7 has only sshd
  listen: 'Restart sshd'

- name: Restart sshd
  service:
   name: ssh
   state: restarted
   enabled: yes
  when:
   - ansible_os_family == 'Debian'
  listen: 'Restart sshd'
